# Generated by Django 5.1.7 on 2025-04-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_orders_payment_token_orders_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_token',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='qr_code',
        ),
    ]
